# Generated by Django 2.1.2 on 2018-10-27 06:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajos',
            name='docfile',
            field=models.FileField(default=django.utils.timezone.now, upload_to='archivos/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trabajos',
            name='categoria',
            field=models.CharField(choices=[('CC', 'Ciencias Computacionales'), ('CT', 'Ciencias de la Tierra'), ('CN', 'Ciencias Naturales'), ('CS', 'Ciencias Sociales'), ('CM', 'Ciencias Medicas')], max_length=2),
        ),
    ]
